### ISSUE TITLE
[CHECKLIST] Restaking API / SDK

### ISSUE THREAD

**Issue by drewstone** [webb-tools/tangle-mpc-sdk#1]
# Description
A restaking sdk that can be used by dApps, CLIs, and NodeJS scripts to interact with the restaking system. The SDK can fetch data, make transactions, etc.

### Requirements
- Everything needs documentation.
- Everything needs to be tested.
- There should be CI in this SDK.
- Should be usable in various environments, such as NodeJS or browsers.
- Codebase should be maintainable, simple, clean, and high quality.
- Public-facing functions should provide clear signature definitions that convey failure, and also friendly error messages. This helps on the developer experience.

### Tasks
- [x] #4
- [ ] #5
- [ ] #6
- [ ] Add testing tools (Jest) into code + CI
- [ ] Publish package every time the `main` branch is updated 

### Questions
1. Do we *need* this for queries?
2. How to design a nice SDK for various applications such as Wallet-as-a-Service (WaaS) infrastructure and Oracles?

### Notes
* There's different levels of abstraction for the SDK, but the lowest one would be simply abstracting the PolkadotJS API calls. We could start there.
* This SDK may also be consumed on the Webb DApp repository whenever interacting with the `jobs` or `roles` pallets.
* **Jobs**: Phase 1: Select some account, Phase 2: When I see requests from that account, the system validates the request and performs the phase 2 jobs. There’s multiple phases that rely on ‘permitted callers’, which means that account are permitted to call and triger other phases.

### Future ideas
* If someone is creating a phase 1 job, and submitting a smart contract as the permitted caller, the SDK could upload the smart contract to a public, verifiable database of contracts, so that the webb dapp can use that database of contracts to verify it. This is already happening on things like Etherscan, but not implemented in tangle as of yet.

**Comment by yuri-xyz** [comment]
Transferring this issue to the [Tangle MPC SDK repository](https://github.com/webb-tools/tangle-mpc-sdk), to be used as the initial point of discussion for the project.

**Comment by drewstone** [comment]
https://github.com/polkadot-js/api/blob/master/packages/api-derive/src/types.ts#L41

**Comment by drewstone** [comment]
### Jobs pallet txes
- Submit job
- Submit job result
- Withdraw rewards

### Roles pallet txes
- Create profile
- Update profile

**Comment by vutuanlinh2k2** [comment]
Working on Roles pallet txes

**Comment by yuri-xyz** [comment]
Initial ideas:
* **Main focus**: Abstracting the jobs and roles pallet in a manner that is as easy to consume as possible, with useful examples and good documentation.
* **Multi-environment requirement**: Need to take this into account, since the SDK would be used in both browser and native environments, so would need to figure out how that would work, for example in non-browser context how would we request transactions to be made by the user?
* **Versioning**: [Semantic Versioning](https://semver.org/), seems to be the most popular option for NPM packages:
  * MAJOR version when you make incompatible API changes
  * MINOR version when you add functionality in a backward compatible manner
  * PATCH version when you make backward compatible bug fixes
* **Documentation**: Focus on having a good README, sections could include `Introduction`, `Installation`, `Quick Start`, `Examples`, and `API Reference`.
  * Public-facing functions should be well-documented using [JSDoc](https://jsdoc.app/), avoid overly-documenting stuff when not needed though (better to have descriptive, self-documenting functions when possible).
* **CI**: Should publish the NPM package once are made to the `main` branch, or if they include `[RELEASE]` in their titles (similar to what is done on Webb Dapp monorepo). If we do end up having tests, then those should be integrated into the CI as well.
* **Testing**: Focus on using unit tests for utility functions, which are easy but crucial to test since they're usually *pure*. For now, doing E2E tests may be over kill until we reach a reasonable level of complexity in the app, or it may also be a good idea to start with testing in mind from the beginning. A popular testing library would be [Jest](https://jestjs.io/).

Additionally:
* We could start the design of the SDK by creating examples of how *we'd like to ideally consume it*. In other words, we create an example that would be how the SDK is used, *and then* we start building with that architecture in mind. Example:

```ts
import TangleMPCSDK, {Role, scaleToTangleUnit, RecordsCheckStatus} from "tangle-mpc-sdk"

const sdk = new TangleMPCSDK({ ... options ... })

// Help stay within bounds, ie. >= min restaking bond and <= max restake amount (50% of staked amount).
const records = sdk.createAllocationHelper()

// scaleToTangleUnit: Convert a Number to TNT amount (18 decimals), in BN form.
records.add(Role.ZkSaaSGroth16, scaleToTangleUnit(100)) // 100 TNT
records.add(Role.ZkSaaSMarlin, scaleToTangleUnit(50)) // 50 TNT

const recordsStatus = records.check()

if (recordsStatus !== RecordsCheckStatus.Ok) {
  // Example: RecordsCheckStatus.NotEnoughBalance, or RecordsCheckStatus.ExceedsMaxRestakingAmount.
  throw new Error(`There was an issue with the allocations: ${recordsStatus}`)
}

const error: Error | null = await sdk.createIndependentProfile({
  records,
  updateIfExists: true
})

if (error === null) {
  console.log("Operation completed!")
}
else {
  console.error(error)
}
```
